/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VendingMachine;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("Hello world!", "app should have a greeting");
    }
}
